name: Build ESP32 Firmware

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v3.3

    steps:
    # Đổi từ @v4 xuống @v2 để tương thích với hệ điều hành cũ trong Docker
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Firmware
      run: |
        . /opt/esp/idf/export.sh
        make defconfig
        make all

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-deauth-firmware
        path: |
          build/esp32-deauth-monitor.bin
          build/bootloader/bootloader.bin
          build/partitions_singleapp.bin
